vycontrol/firewall/urls.py
from django.urls import path

from . import views

app_name = 'firewall'



urlpatterns = [
    path('', views.index, name='firewall-list'),
    path('show/<str:firewall_name>', views.show, name='show'),
    path('firewall-create', views.create, name='firewall-create'),
    path('firewall-remove/<str:firewall_name>', views.firewall_remove, name='firewall-remove'),
    path('firewall-edit/<str:firewall_name>', views.firewall_edit, name='firewall-edit'),
    path('firewall-config/<str:firewall_name>', views.firewall_config, name='firewall-config'),
    path('firewall-global', views.firewall_global, name='firewall-global'),

    path('firewall-addressgroup-list', views.firewall_addressgroup_list, name='firewall-addressgroup-list'),
    path('firewall-addressgroup-add', views.firewall_addressgroup_add, name='firewall-addressgroup-add'),
    path('firewall-addressgroup-del/<str:groupname>', views.firewall_addressgroup_del, name='firewall-addressgroup-del'),
    path('firewall-addressgroup-desc/<str:groupname>', views.firewall_addressgroup_desc, name='firewall-addressgroup-desc'),

    path('firewall-networkgroup-list', views.firewall_networkgroup_list, name='firewall-networkgroup-list'),
    path('firewall-networkgroup-add', views.firewall_networkgroup_add, name='firewall-networkgroup-add'),
    path('firewall-networkgroup-del/<str:groupname>', views.firewall_networkgroup_del, name='firewall-networkgroup-del'),
    path('firewall-networkgroup-desc/<str:groupname>', views.firewall_networkgroup_desc, name='firewall-networkgroup-desc'),    

    path('firewall-portgroup-list', views.firewall_portgroup_list, name='firewall-portgroup-list'),
    path('firewall-portgroup-add', views.firewall_portgroup_add, name='firewall-portgroup-add'),
    path('firewall-portgroup-del/<str:groupname>', views.firewall_portgroup_del, name='firewall-portgroup-del'),
    path('firewall-portgroup-edit/<str:groupname>', views.firewall_portgroup_edit, name='firewall-portgroup-edit'),

    path('zones', views.firewall_zones, name='firewall-zones'),
    path('zones/add', views.firewall_zones_add, name='firewall-zones-add'),
    path('zones/addrule', views.firewall_zones_addrule, name='firewall-zones-addrule'),
    path('zones/removerule/<str:dstzone>/<str:srczone>/<str:firewall>', views.firewall_zones_removerule, name='firewall-zones-removerule'),
    path('zones/edit/<str:zonename>', views.firewall_zones_edit, name='firewall-zones-edit'),
    path('zones/remove/<str:zonename>', views.firewall_zones_remove, name='firewall-zones-remove'),


    path('addrule/<str:firewall_name>', views.addrule, name='addrule'),
    path('editrule/<str:firewall_name>/<str:rulenumber>', views.editrule, name='editrule'),
    path('firewall-removerule/<str:firewall_name>/<str:firewall_rulenumber>', views.firewall_removerule, name='firewall-removerule'),    

]

vycontrol/ntp/urls.py
from django.urls import path

from . import views

app_name = 'ntp'


urlpatterns = [
    path('', views.index, name='ntp-list'),
    path('add', views.add, name='ntp-add'),
    path('remove/<str:server>', views.remove, name='ntp-remove'),
]

vycontrol/vycenter/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

def reload_urlconf(self):
    if settings.ROOT_URLCONF in sys.modules:
        reload(sys.modules[settings.ROOT_URLCONF])
    return import_module(settings.ROOT_URLCONF)

import pprint

from . import views

from django.contrib.auth import views as auth_views


app_name = 'vycenter'

urlpatterns = [
    path('', include('accounts.urls'), name="main-page"),
    path('config/', include('config.urls')),
    path('dashboard/', include('dashboard.urls')),
    #path('', views.vycenter_login, name='vycenter-login'),
    path('admin/', admin.site.urls, name="django-admin"),
    #path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('login/', auth_views.LoginView.as_view(), name="registration-login"),
    path('logout/', auth_views.LogoutView.as_view(), name="registration-logout"),



    path('interface/', include('interface.urls')),

    path('firewall/', include('firewall.urls')),
    path('static/', include('static.urls')),
    path('arp/', include('arp.urls')),
    path('bgp/', include('bgp.urls')),
    path('dhcp/', include('dhcp.urls')),
    path('ipsec/', include('ipsec.urls')),
    path('nat/', include('nat.urls')),
    path('openvpn/', include('openvpn.urls')),
    path('ospf/', include('ospf.urls')),
    path('qos/', include('qos.urls')),
    path('ssh/', include('ssh.urls')),
    path('wanlb/', include('wanlb.urls')),
]

vycontrol/vycontrol/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

def reload_urlconf(self):
    if settings.ROOT_URLCONF in sys.modules:
        reload(sys.modules[settings.ROOT_URLCONF])
    return import_module(settings.ROOT_URLCONF)

import pprint

from . import views

from django.contrib.auth import views as auth_views
from django.urls import path, re_path
from accounts import views as accounts_views


app_name = 'vycontrol'

urlpatterns = [
    path('', accounts_views.index, name='main-page'),
    path('accounts/', include('accounts.urls')),
    path('config/', include('config.urls')),
    path('admin/', admin.site.urls, name="django-admin"),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name="accounts-login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name="accounts-logout"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset.html'), name ='reset_password'),
    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_sent.html'), name ='password_reset_done'),
    path('password_reset_token/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_token.html'), name ='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'accounts/password_reset_complete.html'), name ='password_reset_complete'),
    path('static/', include('static.urls')),
    path('interface/', include('interface.urls')),
    path('firewall/', include('firewall.urls')),
    path('ntp/', include('ntp.urls')),
    path('dnsresolver/', include('dnsresolver.urls')),
]


if settings.VYCONTROL_CRYSPY:
    urlpatterns += [
        path('users/', include('users.urls')),
    ]

vycontrol/firewall/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import redirect
from django.conf import settings
from django.urls import reverse
from django.http import QueryDict


import vyos
import vapilib
import vapi
import vmsg

from slugify import slugify
from performance import timer
from perms import is_authenticated
import perms
import network
import json
import pprint
import types


from libs.vycontrol_filters import get_item
from libs.vycontrol_filters import get_item_port
from libs.vycontrol_filters import get_item_network



@is_authenticated
def index(request):

    #interfaces = vyos.get_interfaces()
    all_instances = perms.instance_getall_by_group(request)
    hostname_default = perms.get_hostname_prefered(request)


    """firewall2 = vapilib.api(
        hostname =      hostname_default,
        api =           'get',
        op =            'showConfig',
        cmd =           {"op": "showConfig", "path": ["firewall"]},
        description =   "get all firewall",
    )"""


    is_superuser = perms.get_is_superuser(request.user)



    firewall_all = vyos.get_firewall_all(hostname_default)
    if firewall_all == False:
        return redirect('firewall:firewall-create')

    if 'name' in firewall_all: 
        for xitem in firewall_all['name']:
            if 'default-action' in firewall_all['name'][xitem]:
                firewall_all['name'][xitem]['default_action'] = firewall_all['name'][xitem]['default-action']
                del firewall_all['name'][xitem]['default-action']

    template = loader.get_template('firewall/list.html')
    context = { 
        #'interfaces': interfaces,
        'instances':                                all_instances,
        'hostname_default':                         hostname_default,
        'firewall_all':                             firewall_all,
        'username':                                 request.user,
        'is_superuser' :                            is_superuser,
    }   
    return HttpResponse(template.render(context, request))

@is_authenticated
def create(request):
        
    #interfaces = vyos.get_interfaces()
    all_instances = perms.instance_getall_by_group(request)
    hostname_default = perms.get_hostname_prefered(request)
    is_superuser = perms.get_is_superuser(request.user)

    if 'name' in request.POST:
        cmd = {"op": "set", "path": ["firewall", "name", request.POST['name']]}
        result1 = vyos.set_config(hostname_default, cmd)
        print(result1)

        if 'description' in request.POST:
            cmd = {"op": "set", "path": ["firewall", "name", request.POST['name'], "description", request.POST['description']]}
            result2 = vyos.set_config(hostname_default, cmd)
            print(result2)

        if 'action' in request.POST:
            cmd = {"op": "set", "path": ["firewall", "name", request.POST['name'], "default-action", request.POST['action']]}
            result3 = vyos.set_config(hostname_default, cmd)
            print(result3)

        return redirect('firewall:firewall-list')

    template = loader.get_template('firewall/create.html')
    context = { 
        #'interfaces': interfaces,
        'instances': all_instances,
        'hostname_default': hostname_default,
        'username': request.user,
        'is_superuser' : is_superuser,
    }   
    return HttpResponse(template.render(context, request))

@is_authenticated
def firewall_removerule(request, firewall_name, firewall_rulenumber):
    all_instances = perms.instance_getall_by_group(request)
    hostname_default = perms.get_hostname_prefered(request)

    firewall = vyos.get_firewall(hostname_default, firewall_name)
    firewall_rule = vyos.get_firewall_rule(hostname_default, firewall_name, firewall_rulenumber)

    if firewall_rule and firewall:
        vyos.delete_route_rule(hostname_default, firewall_name, firewall_rulenumber)

    return redirect('firewall:show', firewall_name)

def changerule(request, firewall_name, mode, rulenumber=None):
    msg = vmsg.msg()

    #interfaces = vyos.get_interfaces()
    all_instances = perms.instance_getall_by_group(request)
    hostname_default = perms.get_hostname_prefered(request)
    is_superuser = perms.get_is_superuser(request.user)

    # get all firewall groups
    firewall_group = {}
    changed = False
    rulenumber_valid = False
    ruledata = {}

    # netservices /etc/services parser
    netservices = network.get_services()

    # firewall groups         
    firewall_group['network-group'] = {}
    firewall_group['address-group'] = {}
    firewall_group['port-group'] = {}
    firewall_group_raw = vapi.get_firewall_group(hostname_default)
    if firewall_group_raw.success:
        if 'network-group' in firewall_group_raw.data:
            firewall_group['network-group'] = firewall_group_raw.data['network-group']

        if 'address-group' in firewall_group_raw.data:
            firewall_group['address-group'] = firewall_group_raw.data['address-group']

        if 'port-group' in firewall_group_raw.data:
            firewall_group['port-group'] = firewall_group_raw.data['port-group']
    
    # edit rule without valid rulenumber
    if mode == "editrule":
        if rulenumber == None:
            msg.add_error("Rule number empty")
        else:
            v = vapi.get_firewall_rulenumber(hostname_default, firewall_name, rulenumber)
            if v.success:
                ruledata = v.data

                # if rule exists control variables are true
                rulenumber_valid = True
            else:
                msg.add_error("There is no rule number inside firewall")

    # mode add rule
    elif mode == "addrule":
        if request.POST.get('rulenumber', None) == None:
            #msg.add_error("Rule number empty")
            # before fill form rule number is empty
            pass
        else:
            rulenumber = request.POST.get('rulenumber')
            if int(rulenumber) >= 1 and int(rulenumber) <= 9999:
                rulenumber_valid = True
                rulenumber = request.POST.get('rulenumber')
            else:
                rulenumber_valid = False
                msg.add_error("Rule number must be between 1 and 9999")

    ###############################################################################################################################################################
    # update rule action
    if rulenumber_valid and request.POST.get('ruleaction', None) != None:
        if request.POST.get('ruleaction') in ["accept", "drop", "reject"]:
            if mode == "editrule" and ruledata['action'] and request.POST.get('ruleaction') == ruledata['action']:
                msg.add_debug("Action: not changed")
            else:
                v = vapi.set_firewall_rule_action(hostname_default, firewall_name, rulenumber, request.POST.get('ruleaction'))
                if v.success == False:
                    msg.add_error("Action: fail to change - " + v.reason)
                else:
                    # updating ruledata
                    ruledata['action'] = request.POST.get('ruleaction')
                    changed = True
                    msg.add_success("Action: updated")
        else:
            msg.add_error("Action invalid")

    ###############################################################################################################################################################
    # update rule status
    if rulenumber_valid and request.POST.get('status', None) != None:
        if mode == "editrule": 
            if request.POST.get('status') == "enable" and "disable" not in ruledata:
                msg.add_debug("Status: not changed")
            elif request.POST.get('status') == "disable" and "disable" in ruledata:
                msg.add_debug("Status: not changed")
            elif request.POST.get('status') == "disable" and "disable" not in ruledata:
                v = vapi.set_firewall_rule_disabled(hostname_default, firewall_name, rulenumber)
                if v.success == False:
                    msg.add_error("Status: failed to disable - " + v.reason)
                else:
                    # updating ruledata
                    ruledata['disable'] = {}
                    ruledata['status'] = 'disabled'
                    changed = True
                    msg.add_success("Status disabled")
            elif request.POST.get('status') == "enable" and "disable" in ruledata:
                v = vapi.set_firewall_rule_enabled(hostname_default, firewall_name, rulenumber)
                if v.success == False:
                    msg.add_error("Status: failed to enable - " + v.reason)
                else:
                    # updating ruledata
                    del ruledata['disable']
                    ruledata['status'] = 'enabled'
                    changed = True
                    msg.add_success("Status: enabled")                    
        elif mode == "addrule":
            if request.POST.get('status') == "disable":
                v = vapi.set_firewall_rule_disabled(hostname_default, firewall_name, rulenumber)
                if v.success == False:
                    msg.add_error("Status: failed to disable - " + v.reason)
                else:
                    # updating ruledata
                    ruledata['disable'] = {}
                    ruledata['status'] = 'disabled'
                    changed = True
                    msg.add_info("Status: disabled")
            else:
                # nothing to do if status = enable
                pass

    ###############################################################################################################################################################
    # update description
    if rulenumber_valid == True and request.POST.get('description', None) != None:

vycontrol/firewall/templates/firewall/addressgroup-desc.html
{% extends "base.html" %}

{% block header_title %}Edit Addressgroup{% endblock %}
{% block section_title %}Edit Addressgroup{% endblock %}

{% block debug %}
{{ firewall_all }}
{{ firewall_networkgroup }}
{% endblock %}


{% block content %}


<script type="text/javascript">
    var networkgroup_data = JSON.parse('{{networks_json|safe}}');
    console.log(networkgroup_data);
</script>

<p class="submenu1">
    <a href="{% url 'firewall:firewall-list' %}">Firewall List</a> | 
    <a href="{% url 'firewall:firewall-create' %}">Create new firewall</a> | 
    <a href="{% url 'firewall:firewall-addressgroup-list' %}">Address Group</a>     | 
    <a href="{% url 'firewall:firewall-networkgroup-list' %}">Network Group</a>  | 
    <a href="{% url 'firewall:firewall-portgroup-list' %}">Port Group</a> |
    <a href="{% url 'firewall:firewall-zones' %}">Zones</a>
</p>
<p class="submenu2">
    <a href="{% url 'firewall:firewall-addressgroup-add' %}">Add network Group</a>
</p>





<form action="{% url 'firewall:firewall-addressgroup-desc' groupname %}" method="post" id="formng">
    {% csrf_token %}

    <p>
        <label for="name">description:</label><br>
        <input type="input" name="description" id="description" value="{{ groupinfo.description }}" size="100" />
    </p>
    
    <p>
        <label for="network">network (CIDR notation):</label><br>
        <input type="input" name="network" id="network" value=""/> (eg 10.10.10.0/24) 
        <input type="button" value="add" id="networkgroup_add">
    </p>

    <p>
        <label for="networkgroup">networks (click to remove)</label><br>
        <select name="networkgroup" id="networkgroup" size="10" style="width: 200px;">
        </select>


        <input type="hidden" name="networkgroup_json" id="networkgroup_json" value="" >
    </p>


    <input type="submit" value="Edit Group">
</form>


<script>
$(document).ready(function () {

    for (network in networkgroup_data) {
        $('#networkgroup').append($('<option>', {
            value: networkgroup_data[network],
            text: networkgroup_data[network]
        }));
    }

    $("#networkgroup_add").click(function () {
        network = $("#network").val();

        if (network !=  "") {
            if ($("#networkgroup option[value='" + network + "']").length == 0) {
                $('#networkgroup').append($('<option>', {
                    value: network,
                    text: network
                }));
            }
        }
    });


    $('#networkgroup').click(function() {
            $(this).find('option:selected').remove();
    });

    // form basic validations
    $("#formng").submit(function(e){
        size = $("#networkgroup option").length
        if (size < 1) {
            alert('Minimum networks is 1');
            e.preventDefault();
            return false;
        }
        
        var groupa = []
        $("#networkgroup option").each(function() {
            groupa.push($(this).val());
        });

        var groupa_json = JSON.stringify(groupa);
        $("#networkgroup_json").val(groupa_json);

        console.log(groupa_json)
        //e.preventDefault();
        //return false;

    });

})




</script>

    


{% endblock %}

vycontrol/firewall/templates/firewall/networkgroup-desc.html
{% extends "base.html" %}

{% block header_title %}Edit Addressgroup{% endblock %}
{% block section_title %}Edit Addressgroup{% endblock %}

{% block debug %}
{{ firewall_all }}
{{ firewall_networkgroup }}
{% endblock %}


{% block content %}


<script type="text/javascript">
    var networkgroup_data = JSON.parse('{{networks_json|safe}}');
    console.log(networkgroup_data);
</script>

<p class="submenu1">
    <a href="{% url 'firewall:firewall-list' %}">Firewall List</a> | 
    <a href="{% url 'firewall:firewall-create' %}">Create new firewall</a> | 
    <a href="{% url 'firewall:firewall-addressgroup-list' %}">Address Group</a>     | 
    <a href="{% url 'firewall:firewall-networkgroup-list' %}">Network Group</a>  | 
    <a href="{% url 'firewall:firewall-portgroup-list' %}">Port Group</a> |
    <a href="{% url 'firewall:firewall-zones' %}">Zones</a>
</p>
<p class="submenu2">
    <a href="{% url 'firewall:firewall-networkgroup-add' %}">Add network Group</a>
</p>





<form action="{% url 'firewall:firewall-networkgroup-desc' groupname %}" method="post" id="formng">
    {% csrf_token %}

    <p>
        <label for="name">description:</label><br>
        <input type="input" name="description" id="description" value="{{ groupinfo.description }}" size="100" />
    </p>
    
    <p>
        <label for="network">network (CIDR notation):</label><br>
        <input type="input" name="network" id="network" value=""/> (eg 10.10.10.0/24) 
        <input type="button" value="add" id="networkgroup_add">
    </p>

    <p>
        <label for="networkgroup">networks (click to remove)</label><br>
        <select name="networkgroup" id="networkgroup" size="10" style="width: 200px;">
        </select>


        <input type="hidden" name="networkgroup_json" id="networkgroup_json" value="" >
    </p>


    <input type="submit" value="Edit Group">
</form>


<script>
$(document).ready(function () {

    for (network in networkgroup_data) {
        $('#networkgroup').append($('<option>', {
            value: networkgroup_data[network],
            text: networkgroup_data[network]
        }));
    }

    $("#networkgroup_add").click(function () {
        network = $("#network").val();

        if (network !=  "") {
            if ($("#networkgroup option[value='" + network + "']").length == 0) {
                $('#networkgroup').append($('<option>', {
                    value: network,
                    text: network
                }));
            }
        }
    });


    $('#networkgroup').click(function() {
            $(this).find('option:selected').remove();
    });

    // form basic validations
    $("#formng").submit(function(e){
        size = $("#networkgroup option").length
        if (size < 1) {
            alert('Minimum networks is 1');
            e.preventDefault();
            return false;
        }
        
        var groupa = []
        $("#networkgroup option").each(function() {
            groupa.push($(this).val());
        });

        var groupa_json = JSON.stringify(groupa);
        $("#networkgroup_json").val(groupa_json);

        console.log(groupa_json)
        //e.preventDefault();
        //return false;

    });

})




</script>

    


{% endblock %}

vycontrol/firewall/templates/firewall/networkgroup-list.html
{% extends "base.html" %}

{% block header_title %}Firewall Group List{% endblock %}
{% block section_title %}Firewall Group List{% endblock %}

{% block debug %}
{{ firewall_networkgroup }}
{% endblock %}

{% block content %}

<p class="submenu1">
    <a href="{% url 'firewall:firewall-list' %}">Firewall List</a> | 
    <a href="{% url 'firewall:firewall-create' %}">Create new firewall</a> | 
    <a href="{% url 'firewall:firewall-addressgroup-list' %}">Address Group</a> | 
    <a href="{% url 'firewall:firewall-portgroup-list' %}">Port Group</a> |
    <a href="{% url 'firewall:firewall-zones' %}">Zones</a>
</p>
<p class="submenu2">
    <a href="{% url 'firewall:firewall-networkgroup-add' %}">Add network Group</a>
</p>


{% if firewall_networkgroup %}
    <table border="1" width="100%">
        <tr>
            <th width="25%">name</th>
            <th width="30%">description</th>
            <th width="25%">actions</th>
        </tr>

    {% for key, value in firewall_networkgroup.items %}       
        {% for ifkey, ifvalue in value.items %}
            <tr>
                <td><a href="{% url 'firewall:firewall-networkgroup-desc' ifkey %}">{{ ifkey }}</a></td>
                {% comment %}<td>{{ ifvalue.network }}</td>{% endcomment %}
                <td>{{ ifvalue.description }}</td>
                <td>
                    <a href="{% url 'firewall:firewall-networkgroup-desc' ifkey %}">Edit</a> | 
                    <a href="{% url 'firewall:firewall-networkgroup-del' ifkey %}">Remove</a>
                </td>                
            </tr>
        {% endfor %}
        
    {% endfor %}

    </table>
{% else %}
    <p>No firewalls.</p>
{% endif %}



{% endblock %}

vycontrol/firewall/templates/firewall/portgroup-list.html
{% extends "base.html" %}

{% block header_title %}Firewall Group List{% endblock %}
{% block section_title %}Firewall Group List{% endblock %}

{% block debug %}
{{ firewall_portgroup }}
{% endblock %}

{% block content %}

<p class="submenu1">
    <a href="{% url 'firewall:firewall-list' %}">Firewall List</a> | 
    <a href="{% url 'firewall:firewall-create' %}">Create new firewall</a> | 
    <a href="{% url 'firewall:firewall-addressgroup-list' %}">Address Group</a> |
    <a href="{% url 'firewall:firewall-networkgroup-list' %}">Network Group</a> |
    <a href="{% url 'firewall:firewall-zones' %}">Zones</a>
</p>
<p class="submenu2">
    <a href="{% url 'firewall:firewall-portgroup-add' %}">Add port group</a>
</p>


{% if firewall_portgroup %}
    <table border="1" width="100%">
        <tr>
            <th width="25%">name</th>
            <th width="30%">description</th>
            <th width="25%">actions</th>
        </tr>

    {% for key, value in firewall_portgroup.items %}       
        {% for ifkey, ifvalue in value.items %}
            <tr>
                <td><a href="{% url 'firewall:firewall-portgroup-edit' ifkey %}">{{ ifkey }}</a></td>
                <td>{{ ifvalue.description }}</td>
                <td>
                    <a href="{% url 'firewall:firewall-portgroup-edit' ifkey %}">Edit</a> | 
                    <a href="{% url 'firewall:firewall-portgroup-del' ifkey %}">Remove</a>
                </td>                
            </tr>
        {% endfor %}
        
    {% endfor %}

    </table>
{% else %}
    <p>No port groups.</p>
{% endif %}



{% endblock %}

vycontrol/firewall/templates/firewall/zones-remove.html
{% extends "base.html" %}

{% block header_title %}Remove Firewall Zone{% endblock %}
{% block section_title %}Remove Firewall Zone{% endblock %}

{% block debug %}

<h3>interfaces</h3>
{{ interfaces|pprint }}

<h3>interfaces_all_names</h3>
{{ interfaces_all_names|pprint }}

<h3>zoneinfo</h3>
{{ zoneinfo|pprint }}

{% endblock %}

{% block content %}

<p class="submenu1">
    <a href="{% url 'firewall:firewall-list' %}">Firewall List</a> | 
    <a href="{% url 'firewall:firewall-create' %}">Create new firewall</a> | 
    <a href="{% url 'firewall:firewall-addressgroup-list' %}">Address Group</a> | 
    <a href="{% url 'firewall:firewall-networkgroup-list' %}">Network Group</a> | 
    <a href="{% url 'firewall:firewall-portgroup-list' %}">Port Group</a> | 
    <a href="{% url 'firewall:firewall-zones' %}">Zones</a>
</p>



{% endblock %}

vycontrol/firewall/templates/firewall/zones.html
{% extends "base.html" %}

{% block header_title %}Firewall Zones{% endblock %}
{% block section_title %}Firewall Zones{% endblock %}

{% block debug %}

{{ allzones_pretty }}

<h3>allzonesrules</h3>
{{ allzonesrules|pprint }} 

{% endblock %}

{% block content %}

<p class="submenu1">
    <a href="{% url 'firewall:firewall-list' %}">Firewall List</a> | 
    <a href="{% url 'firewall:firewall-create' %}">Create new firewall</a> | 
    <a href="{% url 'firewall:firewall-addressgroup-list' %}">Address Group</a> | 
    <a href="{% url 'firewall:firewall-networkgroup-list' %}">Network Group</a> | 
    <a href="{% url 'firewall:firewall-portgroup-list' %}">Port Group</a>
</p>
<p class="submenu2">
    <a href="{% url 'firewall:firewall-zones-add' %}">Add Zone</a> | 
    <a href="{% url 'firewall:firewall-zones-addrule' %}">Add Ruleset</a> 
</p>


<h3>Firewall Zones</h3>

{% if allzones %}

    <table border="1" width="100%">
    <tr>
        <th width="25%">zone</th>
        <th width="50%">description</th>
        <th width="25%">action</th>
    </tr>
    </tr>    
    {% for zone in allzones %}
        <tr>
        <td><a href="{% url 'firewall:firewall-zones-edit' zone.name %}">{{ zone.name }}</a></td>
        <td>{{ zone.description }}</td>
        <td><a href="{% url 'firewall:firewall-zones-remove' zone.name %}">remove</a></td>
        </tr>
    {% endfor %}

    </table>

{% else %}
<p>No firewall zone exists.</p>
{% endif %}    


<h3>Firewall Zones Rules</h3>

{% if allzonesrules %}

    <table border="1" width="100%">
    <tr>
        <th width="25%">zone destination</th>
        <th width="25%">zone source</th>
        <th width="25%">firewall</th>
        <th width="25%">action</th>
    </tr>
    </tr>    
    {% for rule in allzonesrules %}
        <tr>
            <td>{{ rule.dstzone }}</td>
            <td>{{ rule.srczone }}</td>
            <td>{{ rule.firewall }}</td>
            <td><a href="{% url 'firewall:firewall-zones-removerule' rule.dstzone rule.srczone rule.firewall %}">remove</a></td>
        </tr>
    {% endfor %}

    </table>

{% else %}
<p>No firewall zone rules exists.</p>
{% endif %}    


{% endblock %}