vycontrol/config/urls.py
from django.urls import path

from . import views


app_name = 'config'

urlpatterns = [
    path('users-list', views.users_list, name='users-list'),
    path('user-inactivate/<str:username>', views.user_inactivate, name='user-inactivate'),
    path('user-activate/<str:username>', views.user_activate, name='user-activate'),
    path('user-edit/<str:username>', views.user_edit, name='user-edit'),
    path('user-add', views.user_add, name='user-add'),

    path('groups-list', views.groups_list, name='groups-list'),
    path('group-add', views.group_add, name='group-add'),
    path('group-edit/<str:group_name>', views.group_edit, name='group-edit'),
    path('group-activate/<str:group_name>', views.group_activate, name='group-activate'),
    path('group-inactivate/<str:group_name>', views.group_inactivate, name='group-inactivate'),

    path('instance-change/<str:hostname>', views.instance_change, name='instance-change'),
    path('instance-add', views.instance_add, name='instance-add'),
    path('instance-edit/<str:hostname>', views.instance_edit, name='instance-edit'),
    path('instance-conntry/<str:hostname>', views.instance_conntry, name='instance-conntry'),
    path('instance-remove/<str:hostname>', views.instance_remove, name='instance-remove'),
    path('instance-changegroup/<str:hostname>', views.instance_changegroup, name='instance-changegroup'),
    path('instances', views.instances, name='instances'),

]

vycontrol/ntp/urls.py
from django.urls import path

from . import views

app_name = 'ntp'


urlpatterns = [
    path('', views.index, name='ntp-list'),
    path('add', views.add, name='ntp-add'),
    path('remove/<str:server>', views.remove, name='ntp-remove'),
]

vycontrol/vycenter/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

def reload_urlconf(self):
    if settings.ROOT_URLCONF in sys.modules:
        reload(sys.modules[settings.ROOT_URLCONF])
    return import_module(settings.ROOT_URLCONF)

import pprint

from . import views

from django.contrib.auth import views as auth_views


app_name = 'vycenter'

urlpatterns = [
    path('', include('accounts.urls'), name="main-page"),
    path('config/', include('config.urls')),
    path('dashboard/', include('dashboard.urls')),
    #path('', views.vycenter_login, name='vycenter-login'),
    path('admin/', admin.site.urls, name="django-admin"),
    #path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('login/', auth_views.LoginView.as_view(), name="registration-login"),
    path('logout/', auth_views.LogoutView.as_view(), name="registration-logout"),



    path('interface/', include('interface.urls')),

    path('firewall/', include('firewall.urls')),
    path('static/', include('static.urls')),
    path('arp/', include('arp.urls')),
    path('bgp/', include('bgp.urls')),
    path('dhcp/', include('dhcp.urls')),
    path('ipsec/', include('ipsec.urls')),
    path('nat/', include('nat.urls')),
    path('openvpn/', include('openvpn.urls')),
    path('ospf/', include('ospf.urls')),
    path('qos/', include('qos.urls')),
    path('ssh/', include('ssh.urls')),
    path('wanlb/', include('wanlb.urls')),
]

vycontrol/vycontrol/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

def reload_urlconf(self):
    if settings.ROOT_URLCONF in sys.modules:
        reload(sys.modules[settings.ROOT_URLCONF])
    return import_module(settings.ROOT_URLCONF)

import pprint

from . import views

from django.contrib.auth import views as auth_views
from django.urls import path, re_path
from accounts import views as accounts_views


app_name = 'vycontrol'

urlpatterns = [
    path('', accounts_views.index, name='main-page'),
    path('accounts/', include('accounts.urls')),
    path('config/', include('config.urls')),
    path('admin/', admin.site.urls, name="django-admin"),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name="accounts-login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name="accounts-logout"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset.html'), name ='reset_password'),
    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_sent.html'), name ='password_reset_done'),
    path('password_reset_token/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_token.html'), name ='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'accounts/password_reset_complete.html'), name ='password_reset_complete'),
    path('static/', include('static.urls')),
    path('interface/', include('interface.urls')),
    path('firewall/', include('firewall.urls')),
    path('ntp/', include('ntp.urls')),
    path('dnsresolver/', include('dnsresolver.urls')),
]


if settings.VYCONTROL_CRYSPY:
    urlpatterns += [
        path('users/', include('users.urls')),
    ]

vycontrol/config/models.py
from django.db import models
from django.contrib.auth.models import Group
from django.contrib.auth.models import User

class Instance(models.Model):
    hostname = models.CharField(max_length=120, primary_key=True)
    alias = models.CharField(max_length=30)
    port = models.IntegerField()
    key = models.CharField(max_length=100)
    https = models.BooleanField()
    main = models.BooleanField(default=False)
    group = models.ForeignKey(Group, null=True, on_delete=models.SET_NULL)

    
Group.add_to_class('active', models.BooleanField(default=True))

vycontrol/config/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import redirect
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.views.generic.base import TemplateView
from django.conf import settings
from django.urls import reverse

from django.contrib.auth.models import User
from django.contrib.auth.models import Group
from config.models import Instance

import vyos
import perms
import vapi
import vmsg
import viewinfo
import validators
from perms import is_authenticated

from libs.vycontrol_validators import *
from django.template.defaultfilters import register
from libs.vycontrol_filters import get_item

@perms.is_superuser
@is_authenticated
def users_list(request):
    vinfo = viewinfo.prepare(request)

    users = User.objects.all()
    groups = Group.objects.all()

    group_show = []
    for group in groups:
        if group.name != "admin":
            group_show.append(group.name)

    has_group_add = False
    for el in request.POST:
        if el.startswith('group-') and request.POST[el]:
            pos = el.split("-", 1)
            
            el_username = pos[1]
            el_groupname = request.POST[el]
          
            # test also if username is member of admin or superuser, than this one should not being no group
            if el_groupname not in ['admin']:
                try:
                    el_userid = User.objects.get(username=el_username) 
                except User.DoesNotExist:
                    return redirect('config:users_list')

                try:
                    if el_userid.groups.exists():
                        for g in el_userid.groups.all():
                            el_userid.groups.remove(g)
                except Group.DoesNotExist:
                    return redirect('config:users_list')

                if el_groupname == "--remove--":
                    has_group_add = has_group_add  + 1
                else:
                    el_groupadd = Group.objects.get(name=el_groupname) 
                    el_groupadd.user_set.add(el_userid)
                    has_group_add = has_group_add  + 1

    if has_group_add > 0:
        return redirect('config:users-list')


    user_groups = {}
    for user in users:
        #print(user.email)
        user_groups_list = user.groups.all()
        if len(user_groups_list) > 0:
            user_groups[str(user)] = str(user_groups_list[0])
        else:
            user_groups[str(user)] = None

    context = viewinfo.context(vinfo)    
    localcontext = {
        'users' : users,
        'groups': group_show,
        'user_groups': user_groups,
    }
    context.update(localcontext)

    return render(request, 'config/users_list.html', context)


@perms.is_superuser
@is_authenticated
def groups_list(request):
    vinfo = viewinfo.prepare(request, title="Groups list")

    groups = Group.objects.all()

    context = viewinfo.context(vinfo)    
    localcontext = {
        'groups' : groups,
    }
    context.update(localcontext)

    return render(request, 'config/groups_list.html', context)   


@is_authenticated
def instances(request):
    vinfo = viewinfo.prepare(request, "Instances List")

    if vinfo.hostname_default == None:
        if vinfo.all_instances.count() > 0:
            for i in vinfo.all_instances:
                instance_default(request, i.hostname)
                
        else:
            return redirect('config:instance-add')

    groups = Group.objects.filter(active=True)


    context = viewinfo.context(vinfo)    
    localcontext = {
        'groups' : groups,
    }

    context.update(localcontext)

    return render(request, 'config/instances.html', context)   


@perms.is_superuser
@is_authenticated
def instance_add(request):
    vinfo = viewinfo.prepare(request)

    if len(request.POST) > 0:
        instance = Instance()
        instance.alias = request.POST['alias']
        instance.hostname = request.POST['hostname']
        instance.port = request.POST['port']
        instance.key = request.POST['key']
        if 'https' in request.POST:
            instance.https = request.POST['https']
        else:
            instance.https = False
        instance_id = instance.save()
        return redirect('config:instances')
    else:
        instance_id = 0

    context = viewinfo.context(vinfo)    
    localcontext = {
    }
    if len(vinfo.all_instances) == 0:
        localcontext['noinstance'] = True
    context.update(localcontext)

    return render(request, 'config/instance_add.html', context)  

@perms.is_superuser
@is_authenticated
def group_add(request):
    vinfo = viewinfo.prepare(request)

    error_message = None

    if len(request.POST) > 0 and 'name' in request.POST:
        try:
            group_get = Group.objects.get(name=request.POST['name'])       
            error_message = 'Group already exists'
        except Group.DoesNotExist:
            group_create = Group(name=request.POST['name'])
            group_create.save()
            return redirect('config:groups-list')
    else:
        instance_id = 0

    context = viewinfo.context(vinfo)    
    localcontext = {
        'error_message' : error_message,
    }
    context.update(localcontext)

    return render(request, 'config/group_add.html', context) 

@perms.is_superuser
@is_authenticated    
def user_add(request):
    vinfo = viewinfo.prepare(request)

    error_message = None

    count = 0
    name = ''
    if 'name' in request.POST:
        name = request.POST['name']
        count += 1

    username = ''
    if 'username' in request.POST:
        username = request.POST['username']
        count += 1

    password = ''
    if 'password' in request.POST:
        password = request.POST['password']
        count += 1

    email = ''
    if 'email' in request.POST:
        email = request.POST['email']                        
        count += 1

    if count >= 4:
        try:
            user = User.objects.get(username=username)       
            error_message = 'Username already exists'
        except User.DoesNotExist:
            user_create = User(
                username=username,
                email=email,
                password=password,
                last_name=name
            )
            user_create.save()
            return redirect('config:users-list')

    context = viewinfo.context(vinfo)    
    localcontext = {
        'error_message' :   error_message,
        'name' :            name,
        'username' :        username,
        'password' :        password,
        'email' :           email,
    }
    context.update(localcontext)

    return render(request, 'config/user_add.html', context) 

@perms.is_superuser
@is_authenticated    
def user_inactivate(request, username):
    vinfo = viewinfo.prepare(request)
    if validator_letters_numbers(username):
        user = User.objects.get(username=username)
        user.is_active = False
        user.save()

    return redirect('config:users-list')

@perms.is_superuser
@is_authenticated    
def user_activate(request, username):
    vinfo = viewinfo.prepare(request)
    if validator_letters_numbers(username):
        user = User.objects.get(username=username)
        user.is_active = True
        user.save()

    return redirect('config:users-list')

    
@perms.is_superuser
@is_authenticated    
def user_edit(request, username):
    vinfo = viewinfo.prepare(request)
    if validator_letters_numbers(username):
        user = User.objects.get(username=username)
        if request.POST.get('email', None) != None:
            email_new = request.POST.get('email').strip()

            if validators.email(email_new):
                user.email = email_new
                user.save()
    
        if request.POST.get('pass1', None) != None and request.POST.get('pass2', None) != None:
            if request.POST.get('pass1') == request.POST.get('pass2'):
                pass_new = request.POST.get('pass1').strip()
                if pass_new != '':
                    user.set_password(pass_new)
                    user.save()
    else:
        return redirect('config:users-list')

    context = viewinfo.context(vinfo)    
    localcontext = {
        'user':             user,
    }
    context.update(localcontext)

    return render(request, 'config/user_edit.html', context) 


@is_authenticated
def instance_conntry(request, hostname):
    vinfo = viewinfo.prepare(request)

    if perms.user_has_hostname_access(request.user, hostname) == False:
        return redirect('config:instances')

    # permcheck
    instance = Instance.objects.get(hostname=hostname)
    connected = vyos.conntry(hostname)
    if connected == True:
        request.session['hostname'] = hostname

    context = viewinfo.context(vinfo)    
    localcontext = {
        'instance':         instance,
        "connected":        connected,
    }
    context.update(localcontext)

    return render(request, 'config/instance_conntry.html', context) 

# get default instance or set default instance 
@is_authenticated
def instance_change(request, hostname = False):
    vinfo = viewinfo.prepare(request)

    #method = None  
    if hostname != "__none__":
        #method = "param"
        pass
    elif hostname == "__none__":
        #method = "get"
        hostname = request.POST.get('vyos-id', False)
 
    # permcheck
    if hostname != False:
        if perms.user_has_hostname_access(request.user, hostname) == False:
            return redirect('config:instances')

        try:
            instance = Instance.objects.get(hostname=hostname)
        except Instance.DoesNotExist:
            print("instance not exists: " + str(hostname))
            return redirect('config:instances')    

        if instance:
            connected = vyos.conntry(hostname)
            # show some error when not connected
            if connected == True:

vycontrol/config/templates/config/group_add.html
{% extends "base.html" %}

{% block header_title %}Add new group{% endblock %}
{% block section_title %}Add new group{% endblock %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'config:group-add' %}" method="post">
{% csrf_token %}

<p>
<label for="alias">Name</label><br>
<input type="text" name="name" id="name" value="{{ name }}" size="90">
</p>


<input type="submit" value="Add group">
</form>



{% endblock %}

vycontrol/config/templates/config/group_edit.html
{% extends "base.html" %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'config:group-edit' group %}" method="post">
{% csrf_token %}

<p>Name only accept letters, numbers and _-.</p>

<p>
    <label for="alias">Name</label><br>
    <input type="text" name="name" id="name" value="{{ group.name }}" size="60">
</p>


<input type="submit" value="Edit user">
</form>



{% endblock %}

vycontrol/config/templates/config/groups_list.html
{% extends "base.html" %}

{% block debug %}
{{ groups }}
{{ x }}
{% endblock %}

{% block content %}

<p class="submenu1">
    {% if is_superuser %}<a href="{% url 'config:group-add' %}">Add new group</a>{% endif %}
</p>
<p class="submenu2"></p>



{% if groups %}

    <table border="1" width="100%">
    <tr>
        <th>name</th>
        <th>status</th>
        <th>actions</th>
    </tr>

    {% for group in groups %}
    <tr>
        <td>{{ group }}</td>
        <td>{% if group.active == True %}active{% else %}inactive{% endif %}</td>
        <td>
            <a href="{% url 'config:group-edit' group %}">edit</a> | 
            {% if group.active == True %}<a href="{% url 'config:group-inactivate' group %}">inactivate</a>{% else %}<a href="{% url 'config:group-activate' group %}">activate</a>{% endif %}
        </td>

    </tr>

    {% endfor %}

    </table>   
{% else %}
    <p>No groups.</p>
{% endif %}


{% endblock %}

vycontrol/config/templates/config/instance_add.html
{% extends "base.html" %}


{% block header_title %}Add new instance{% endblock %}
{% block section_title %}Add new instance{% endblock %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<p class="margin-topbottom">VyOS vyos-api need to be configurated using vyos cli/ssh according <a href="https://docs.vyos.io/" target="_blank">VyOS documentation</a>.</p>

<form action="{% url 'config:instance-add' %}" method="post">


{% csrf_token %}

<p>
<label for="alias">Alias</label><br>
<input type="text" name="alias" id="alias" value="{{ alias }}" size="20">
</p>

<p>
<label for="hostname">VyOS API Hosname/IP</label><br>
<input type="text" name="hostname" id="hostname" value="{{ hostname }}" size="60">
</p>

<p>
<label for="port">VyOS API TCP Port</label><br>
<input type="text" name="port" id="port" value="{{ port }}" size="5">
</p>

<p>
<label for="key">VyOS API Key</label><br>
<input type="text" name="key" id="key" value="{{ key }}" size="60">
</p>


<p>
<label for="https">VyOS is https?</label><br>
<input type="checkbox" name="https" id="https" value="1" checked="checked">
</p>

<input type="submit" value="Add Instance">
</form>



{% endblock %}

vycontrol/config/templates/config/instance_conntry.html
{% extends "base.html" %}

{% block header_title %}List instances{% endblock %}
{% block section_title %}List instances{% endblock %}

{% block content %}

{% if instance %}
    {% if connected == True %}
        <div class="alert-ok">Instance connected</div>
    {% else %}
        <div class="alert-nok">Instance not connected</div>
    {% endif %}

    <table border="1" width="100%">
    <tr><th>alias</th><th>hostname</th><th>port</th><th>https</th></tr>

    <tr>
        <td>{{ instance.alias }}</td>
        <td>{{ instance.hostname }}</td>
        <td>{{ instance.port }}</td>
        <td>{{ instance.https }}</td>
    </tr>


    </table>   
{% else %}
    <p>No instances.</p>
{% endif %}


{% endblock %}

vycontrol/config/templates/config/instance_edit.html
{% extends "base.html" %}


{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<p class="margin-topbottom">VyOS vyos-api need to be configurated using vyos cli/ssh according <a href="https://docs.vyos.io/" target="_blank">VyOS documentation</a>.</p>

<form action="{% url 'config:instance-edit' instance.hostname %}" method="post">


{% csrf_token %}

<p>
<label for="alias">Alias</label><br>
<input type="text" name="alias" id="alias" value="{{ instance.alias }}" size="20">
</p>

<p>
<label for="hostname">VyOS API Hosname/IP</label><br>
<input type="text" name="hostname" id="hostname" value="{{ instance.hostname }}" size="60">
</p>

<p>
<label for="port">VyOS API TCP Port</label><br>
<input type="text" name="port" id="port" value="{{ instance.port }}" size="6">
</p>

<p>
<label for="key">VyOS API Key</label><br>
<input type="text" name="key" id="key" value="{{ instance.key }}" size="60">
</p>


<p>
<label for="https">VyOS is https?</label><br>
<input type="checkbox" name="https" id="https" value="1" {% if instance.https == True %}checked="checked"{% endif %}>
</p>

<input type="submit" value="Edit Instance">
</form>



{% endblock %}

vycontrol/config/templates/config/instances.html
{% extends "base.html" %}


{% block debug %}
    {% for instance in instances %}
    {{ instance }} - {{ instance.group.name }}
    {% endfor %}
{% endblock %}

{% block content %}

<p class="submenu1">
    {% if is_superuser %}<a href="{% url 'config:instance-add' %}">Add new instance</a>{% endif %}
</p>
<p class="submenu2"></p>


{% if instances %}

    <table border="1" width="100%">
    <tr>
        <th>alias</th>
        <th>hostname</th>
        <th>port</th>
        <th>key</th>
        <th>https</th>
        <th>test connection</th>
        <th>default</th>
        <th>group access</th>
        {% if is_superuser %}<th>remove</th>{% endif %}
    </tr>

    {% for instance in instances %}
    <tr>
        <td>{{ instance.alias }}</td>
        <td><a href="{% url 'config:instance-edit' instance.hostname %}">{{ instance.hostname }}</a></td>
        <td>{{ instance.port }}</td>
        <td>show</td>
        <td>{{ instance.https }}</td>
        <td><a href="{% url 'config:instance-conntry' instance.hostname %}">test</a></td>
        <td>{% if instance.main == True %}default{% else %}<a href="{% url 'config:instance-change' instance.hostname %}">set default</a>{% endif %}</td>
        {%if is_superuser %}
        <td><form action="{% url 'config:instance-changegroup' instance.hostname %}" method="post">
            {% csrf_token %}

            <select name="group" onchange="this.form.submit()">
                {% if groups %}
                    {% for group in groups %}
                        <option value="{{ group }}" {% if group == instance.group %}selected{% endif %}>{{ group }}</option>
                    {% endfor %}
                {% endif %}
            </select>
        </form>
        </td>
        {% else %}
        <td>{{ instance.group }}</td>
        {% endif %}
        {% if is_superuser %}
            <td>{% if instance.main == True %}-{% else %}<a href="{% url 'config:instance-remove' instance.hostname %}">remove</a>{% endif %}</td>
        {% endif %}
    </tr>

    {% endfor %}

    </table>   
{% else %}
    <p>No instances.</p>
{% endif %}


{% endblock %}

vycontrol/config/templates/config/user_add.html
{% extends "base.html" %}

{% block header_title %}Add new user{% endblock %}
{% block section_title %}Add new user{% endblock %}

{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'config:user-add' %}" method="post">
{% csrf_token %}

<p>
    <label for="alias">Name</label><br>
    <input type="text" name="name" id="name" value="{{ name }}" size="60">
</p>

<p>
    <label for="alias">Email</label><br>
    <input type="text" name="email" id="email" value="{{ email }}" size="60">
</p>

<p>
    <label for="alias">Username</label><br>
    <input type="text" name="username" id="username" value="{{ name }}" size="30">
</p>

<p>
    <label for="alias">Password</label><br>
    <input type="password" name="password" id="password" value="{{ password }}" size="30">
</p>

<input type="submit" value="Add user">
</form>



{% endblock %}

vycontrol/config/templates/config/user_edit.html
{% extends "base.html" %}

{% block header_title %}User edit{% endblock %}
{% block section_title %}User edit{% endblock %}

{% block debug %}
{{ user }}
{% endblock %}


{% block content %}


<form method="post" action="{% url 'config:user-edit' user %}">
{% csrf_token %}
<table width="100%" border="1">
    <tr>
        <th width="50%">name</th>
        <td>{{ user.last_name }}</td>
    </tr>
    <tr>
        <th width="50%">username</th>
        <td>{{ user }}</td>
    </tr>    
    <tr>
        <th width="50%">email</th>
        <td><input type="text" name="email" id="email" value="{{ user.email }}"></td>
    </tr>
</table>

<h2>Change password (optional)</h2>
<table width="100%" border="1">
    <tr>
        <th width="50%">password</th>
        <td><input type="password" name="pass1" id="pass1"></td>
    </tr>
    <tr>
        <th width="50%">confirm</th>
        <td><input type="password" name="pass2" id="pass2"></td>
    </tr>
</table>

<input type="submit" value="update profile">

    
</form>



{% endblock %}

vycontrol/config/templates/config/users_list.html
{% extends "base.html" %}

{% block debug %}
{{ users }}
{{ groups }}
{{ user_groups }}
{{ username }}
{% endblock %}


{% block header_title %}Users list{% endblock %}
{% block section_title %}Users list{% endblock %}


{% block content %}


<p class="submenu1">
    {% if is_superuser %}<a href="{% url 'config:user-add' %}">Add new user</a>{% endif %}
</p>
<p class="submenu2"></p>



{% if users %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'config:users-list' %}" method="post">
    {% csrf_token %}


    
    <table border="1" width="100%">
    <tr>
        <th>name</th>
        <th>email</th>
        <th>status</th>
        <th>group</th>
        <th>actions</th>
    </tr>

    {% for user in users %}
    <tr>
        <td>{{ user }}</td>
        <td>{{ user.email }}</td>
        <td>{% if user.is_active == True %}active{% else %}inactive{% endif %}</td>
        <td><select id="group-{{ user }}" name="group-{{ user }}"><option value="--remove--">None</option>
            {% if groups != False %}
                {% for fkey in groups %}    
                    <option value="{{ fkey }}" {% if user_groups|get_item:user.username == fkey %}selected="selected"{% endif %}>{{ fkey }}</option>
                {% endfor %}
            {% endif %}
        </select></td>
        <td>
            <a href="{% url 'config:user-edit' user %}">edit</a> | 
            {% if user.is_active == True %}<a href="{% url 'config:user-inactivate' user %}">inactivate</a>{% else %}<a href="{% url 'config:user-activate' user %}">activate</a>{% endif %}
        </td>


    </tr>

    {% endfor %}

    </table>  
    

    <div class="separe-form" class="text-right">
        <input type="submit" value="Set Groups">
    </div>
    
    </form>
    
    
{% else %}
    <p>No users.</p>
{% endif %}


{% endblock %}