vycontrol/accounts/urls.py
from django.urls import path
from django.urls import include
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import redirect
from django.conf import settings
from django.contrib.auth import views as auth_views


import vyos

from . import views

app_name = 'accounts'

urlpatterns = [
   path('', views.profile, name='accounts-profile'),
]

vycontrol/config/urls.py
from django.urls import path

from . import views


app_name = 'config'

urlpatterns = [
    path('users-list', views.users_list, name='users-list'),
    path('user-inactivate/<str:username>', views.user_inactivate, name='user-inactivate'),
    path('user-activate/<str:username>', views.user_activate, name='user-activate'),
    path('user-edit/<str:username>', views.user_edit, name='user-edit'),
    path('user-add', views.user_add, name='user-add'),

    path('groups-list', views.groups_list, name='groups-list'),
    path('group-add', views.group_add, name='group-add'),
    path('group-edit/<str:group_name>', views.group_edit, name='group-edit'),
    path('group-activate/<str:group_name>', views.group_activate, name='group-activate'),
    path('group-inactivate/<str:group_name>', views.group_inactivate, name='group-inactivate'),

    path('instance-change/<str:hostname>', views.instance_change, name='instance-change'),
    path('instance-add', views.instance_add, name='instance-add'),
    path('instance-edit/<str:hostname>', views.instance_edit, name='instance-edit'),
    path('instance-conntry/<str:hostname>', views.instance_conntry, name='instance-conntry'),
    path('instance-remove/<str:hostname>', views.instance_remove, name='instance-remove'),
    path('instance-changegroup/<str:hostname>', views.instance_changegroup, name='instance-changegroup'),
    path('instances', views.instances, name='instances'),

]

vycontrol/firewall/urls.py
from django.urls import path

from . import views

app_name = 'firewall'



urlpatterns = [
    path('', views.index, name='firewall-list'),
    path('show/<str:firewall_name>', views.show, name='show'),
    path('firewall-create', views.create, name='firewall-create'),
    path('firewall-remove/<str:firewall_name>', views.firewall_remove, name='firewall-remove'),
    path('firewall-edit/<str:firewall_name>', views.firewall_edit, name='firewall-edit'),
    path('firewall-config/<str:firewall_name>', views.firewall_config, name='firewall-config'),
    path('firewall-global', views.firewall_global, name='firewall-global'),

    path('firewall-addressgroup-list', views.firewall_addressgroup_list, name='firewall-addressgroup-list'),
    path('firewall-addressgroup-add', views.firewall_addressgroup_add, name='firewall-addressgroup-add'),
    path('firewall-addressgroup-del/<str:groupname>', views.firewall_addressgroup_del, name='firewall-addressgroup-del'),
    path('firewall-addressgroup-desc/<str:groupname>', views.firewall_addressgroup_desc, name='firewall-addressgroup-desc'),

    path('firewall-networkgroup-list', views.firewall_networkgroup_list, name='firewall-networkgroup-list'),
    path('firewall-networkgroup-add', views.firewall_networkgroup_add, name='firewall-networkgroup-add'),
    path('firewall-networkgroup-del/<str:groupname>', views.firewall_networkgroup_del, name='firewall-networkgroup-del'),
    path('firewall-networkgroup-desc/<str:groupname>', views.firewall_networkgroup_desc, name='firewall-networkgroup-desc'),    

    path('firewall-portgroup-list', views.firewall_portgroup_list, name='firewall-portgroup-list'),
    path('firewall-portgroup-add', views.firewall_portgroup_add, name='firewall-portgroup-add'),
    path('firewall-portgroup-del/<str:groupname>', views.firewall_portgroup_del, name='firewall-portgroup-del'),
    path('firewall-portgroup-edit/<str:groupname>', views.firewall_portgroup_edit, name='firewall-portgroup-edit'),

    path('zones', views.firewall_zones, name='firewall-zones'),
    path('zones/add', views.firewall_zones_add, name='firewall-zones-add'),
    path('zones/addrule', views.firewall_zones_addrule, name='firewall-zones-addrule'),
    path('zones/removerule/<str:dstzone>/<str:srczone>/<str:firewall>', views.firewall_zones_removerule, name='firewall-zones-removerule'),
    path('zones/edit/<str:zonename>', views.firewall_zones_edit, name='firewall-zones-edit'),
    path('zones/remove/<str:zonename>', views.firewall_zones_remove, name='firewall-zones-remove'),


    path('addrule/<str:firewall_name>', views.addrule, name='addrule'),
    path('editrule/<str:firewall_name>/<str:rulenumber>', views.editrule, name='editrule'),
    path('firewall-removerule/<str:firewall_name>/<str:firewall_rulenumber>', views.firewall_removerule, name='firewall-removerule'),    

]

vycontrol/interface/urls.py
from django.urls import path

from . import views

app_name = 'interface'

urlpatterns = [
    path('', views.index, name='interface-list'),
    path('interface-show/<slug:interface_type>/<str:interface_name>', views.interface_show, name='interface-show'),
    path('interface-firewall/<slug:interface_type>/<str:interface_name>', views.interface_firewall, name='interface-firewall'),
    path('interface-set-firewall/<slug:interface_type>/<str:interface_name>', views.interface_set_firewall, name='interface-set-firewall'),
    path('interface-set/<slug:interface_type>/<str:interface_name>', views.interface_set, name='interface-set'),
    path('interface-delete/<slug:interface_type>/<str:interface_name>/<str:interface_vif>', views.interface_delete, name='interface-delete'),
    path('interface-delete/<slug:interface_type>/<str:interface_name>', views.interface_delete, name='interface-delete'),
    path('interface-add', views.interface_add, name='interface-add'),
    path('interface-add-vlan/<slug:interface_type>/<str:interface_name>', views.interface_add_vlan, name='interface-add-vlan'),
    path('interface-add-vlan', views.interface_add_vlan, name='interface-add-vlan'),


]

vycontrol/ntp/urls.py
from django.urls import path

from . import views

app_name = 'ntp'


urlpatterns = [
    path('', views.index, name='ntp-list'),
    path('add', views.add, name='ntp-add'),
    path('remove/<str:server>', views.remove, name='ntp-remove'),
]

vycontrol/vycenter/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

def reload_urlconf(self):
    if settings.ROOT_URLCONF in sys.modules:
        reload(sys.modules[settings.ROOT_URLCONF])
    return import_module(settings.ROOT_URLCONF)

import pprint

from . import views

from django.contrib.auth import views as auth_views


app_name = 'vycenter'

urlpatterns = [
    path('', include('accounts.urls'), name="main-page"),
    path('config/', include('config.urls')),
    path('dashboard/', include('dashboard.urls')),
    #path('', views.vycenter_login, name='vycenter-login'),
    path('admin/', admin.site.urls, name="django-admin"),
    #path('change-password/', auth_views.PasswordChangeView.as_view()),
    path('login/', auth_views.LoginView.as_view(), name="registration-login"),
    path('logout/', auth_views.LogoutView.as_view(), name="registration-logout"),



    path('interface/', include('interface.urls')),

    path('firewall/', include('firewall.urls')),
    path('static/', include('static.urls')),
    path('arp/', include('arp.urls')),
    path('bgp/', include('bgp.urls')),
    path('dhcp/', include('dhcp.urls')),
    path('ipsec/', include('ipsec.urls')),
    path('nat/', include('nat.urls')),
    path('openvpn/', include('openvpn.urls')),
    path('ospf/', include('ospf.urls')),
    path('qos/', include('qos.urls')),
    path('ssh/', include('ssh.urls')),
    path('wanlb/', include('wanlb.urls')),
]

vycontrol/vycontrol/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

def reload_urlconf(self):
    if settings.ROOT_URLCONF in sys.modules:
        reload(sys.modules[settings.ROOT_URLCONF])
    return import_module(settings.ROOT_URLCONF)

import pprint

from . import views

from django.contrib.auth import views as auth_views
from django.urls import path, re_path
from accounts import views as accounts_views


app_name = 'vycontrol'

urlpatterns = [
    path('', accounts_views.index, name='main-page'),
    path('accounts/', include('accounts.urls')),
    path('config/', include('config.urls')),
    path('admin/', admin.site.urls, name="django-admin"),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name="accounts-login"),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name="accounts-logout"),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name = 'accounts/password_reset.html'), name ='reset_password'),
    path('password_reset_sent/', auth_views.PasswordResetDoneView.as_view(template_name = 'accounts/password_reset_sent.html'), name ='password_reset_done'),
    path('password_reset_token/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'accounts/password_reset_token.html'), name ='password_reset_confirm'),
    path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = 'accounts/password_reset_complete.html'), name ='password_reset_complete'),
    path('static/', include('static.urls')),
    path('interface/', include('interface.urls')),
    path('firewall/', include('firewall.urls')),
    path('ntp/', include('ntp.urls')),
    path('dnsresolver/', include('dnsresolver.urls')),
]


if settings.VYCONTROL_CRYSPY:
    urlpatterns += [
        path('users/', include('users.urls')),
    ]

vycontrol/vycontrol/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

import vyos

from config.models import Instance


def vycontrol_login(request):
    
    template = loader.get_template('login.html')
    context = {
    }
    return HttpResponse(template.render(context, request))

vycontrol/vycontrol/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  <title>{% if title %}{{ title }}{% else %}{% block header_title %}{% endblock %}{% endif %} - VyControl</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon"> 
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
  integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
  crossorigin="anonymous">
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css"
  integrity="sha256-+bdRwc0NKw+Rhi25h/7Z3aSHWLFeb0LKZ3lrRfSyFwI=" 
  crossorigin="anonymous">    
  <script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" 
  integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" 
  crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static "main.css" %}?{% random_int 100000 500000 %} ">
  <script src="{% static "vycontrol.js" %}?{% random_int 100000 500000 %} "></script>  
  </head>
  <body >

    <div class="container" id="menu-logotop" >
      <div id="menu-topline"></div>
        
      <div class="row ">
        <div class="col-3 ">
          
        </div>
        <div class="col-9">
          {% if not noinstance %}
            <form action="{% url 'config:instance-change' '--none--' %}" method="post" id="instancedefault">
              {% csrf_token %}


              <p class="text-right menu-config">
              
                <select name="vyos-id" id="vyos-id" onchange="this.form.submit();">
                  {% for instance in instances %}
                  <option value="{{instance.hostname}}" {% if hostname_default == instance.hostname %}selected="selected"{% endif %}>{{instance.alias}}</option>
                  {% endfor %}
            
                  
                
                </select>
              

                <span id="menu-username"><a href="{%  url 'accounts:accounts-profile' %}"><i class="material-icons" id="icon-username">person</i>{{ username }}</a></span> <span id="vycontrol-config-menu"> <a href="{% url 'accounts-logout' %}">Logout</a></span>


            </p>
            </form>
          {% endif %}
        </div>
      </div>
    </div>

<div class="container" id="central">
  <div class="row">
    <div class="col-3 menu">

      <p class="text-center">
        <h1 align="center"><a href="/"><img src="https://storage.googleapis.com/vycontrol/logos/logotxt.png?x" width="170"  height="30" alt="vycontrol"></a></h1>
      </p>

    {% if not noinstance %}
      <h2>Router</h2>

      <ul class="menuleft">
      <li><a href="{% url 'interface:interface-list' %}">Interfaces</a></li>
      <li><a href="{% url 'firewall:firewall-list' %}">Firewall</a></li>
      <li><a href="{% url 'static:static-list' %}">Static Routes</a></li>
      <li><a href="{% url 'dnsresolver:dnsresolver-list' %}">DNS resolver</a></li>
      <li><a href="{% url 'ntp:ntp-list' %}">NTP</a></li>
      </ul>
      
  
      {% if is_superuser %}
      <h2>VyControl Administrator</h2>
      <ul class="menuleft">
      <li><a href="{% url 'config:instances' %}">Instances</a></li>
      <li><a href="{% url 'config:users-list' %}">Users</a></li>
      <li><a href="{% url 'config:groups-list' %}">Groups</a></li>
      </ul>
      {% else %}
      <h2>VyControl</h2>
      <ul class="menuleft">
      <li><a href="{% url 'config:instances' %}">Instances</a></li>
      </ul>
      {% endif %}
    {% endif %}

    </div>
    <div class="col content">
        <h2>{% if title %}{{ title }}{% else %}{% block section_title %}{% endblock %}{% endif %}</h2>

        {% block submenu %}{% endblock %}

        {% for m in msg %}
          {% if forloop.first %}  
          <h2 id="msgs-header">Save result</h2>
          <ul id="msgs">
          {% endif %}
            <li class="msgs_{{ m.msg_type }}">{{ m.msg_type }} - {{ m.msg }}</li>
          {% if forloop.last %}  
          </ul>
          {% endif %}        
        {% endfor %}



        {% block content %}{% endblock %}
    </div>
  </div>


</div>


{% if debugactive == True %}
<div class="container" id="debug">
  <h3>Debug</h3>
  <pre>
  {% block debug %}{% endblock %}
</pre>
</div>
{% endif %}

{% if vycontrol_credits %}
<hr>
<div class="container" id="credits">
VyControl
</div>
{% endif %}

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

vycontrol/vycontrol/templates/base_not_installed.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>{% block header_title %}{% endblock %} - VyControl</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon"> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css"
    integrity="sha256-+bdRwc0NKw+Rhi25h/7Z3aSHWLFeb0LKZ3lrRfSyFwI=" 
    crossorigin="anonymous">    
    <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" 
    integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" 
    crossorigin="anonymous"></script>
  
    <link rel="stylesheet" href="{% static "main.css" %}?{% random_int 100000 500000 %} ">
    <script src="{% static "vycontrol.js" %}?{% random_int 100000 500000 %} "></script>  
    </head>
  <body >
    
    

    <div class="container" id="menu-logotop" >
      <div id="menu-topline"></div>
        
      <div class="row ">
        <div class="col-3 ">
          
        </div>
        <div class="col-9">
            <p class="text-right menu-config">

            


          </p>
        </div>
      </div>
    </div>

<div class="container" id="central">
  <div class="row">
    <div class="col-3 menu">

      <p class="text-center">
        <h1 align="center"><a href="/"><img src="https://storage.googleapis.com/vycontrol/logos/logotxt.png?x" width="170"  height="30" alt="vycontrol"></a></h1>
      </p>



    </div>
    <div class="col content">
        <h2>{% block section_title %}{% endblock %}</h2>
        {% block content %}{% endblock %}
    </div>
  </div>


</div>


{% if debugactive == True %}
<div class="container" id="debug">
  <h3>Debug</h3>
  <pre>
  {% block debug %}{% endblock %}
</pre>
</div>
{% endif %}

{% if creditsactive %}
<hr>
<div class="container" id="credits">
VyControl
</div>
{% endif %}

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

vycontrol/vycontrol/templates/base_not_logged.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <title>{% if header_title %}{{ header_title }}{% else %}{% block header_title %}{% endblock %}{% endif %} - VyControl</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="shortcut icon" href="data:image/x-icon;," type="image/x-icon"> 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
    crossorigin="anonymous">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css"
    integrity="sha256-+bdRwc0NKw+Rhi25h/7Z3aSHWLFeb0LKZ3lrRfSyFwI=" 
    crossorigin="anonymous">    
    <script
    src="https://code.jquery.com/jquery-3.6.0.min.js"
    integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
    crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" 
    integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" 
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static "main.css" %}?{% random_int 100000 500000 %} ">
    <script src="{% static "vycontrol.js" %}?{% random_int 100000 500000 %} "></script>  
    </head>
  <body >
    
    

    <div class="container" id="menu-logotop" >
      <div id="menu-topline"></div>
        
      <div class="row ">
        <div class="col-3 ">
          
        </div>
        <div class="col-9">
            <p class="text-right menu-config">

            

              <span id="vycontrol-config-menu"><a href="{% url 'accounts-login' %}">Login</a></span>

          </p>
        </div>
      </div>
    </div>

<div class="container" id="central">
  <div class="row">
    <div class="col-3 menu">

      <p class="text-center">
        <h1 align="center"><a href="/"><img src="https://storage.googleapis.com/vycontrol/logos/logotxt.png?x" width="170"  height="30" alt="vycontrol"></a></h1>
      </p>



    </div>
    <div class="col content">
        <h2>{% if header_title %}{{ header_title }}{% else %}{% block section_title %}{% endblock %}{% endif %}</h2>

        {% for m in msg %}
          {% if forloop.first %}  
          <h2 id="msgs-header">Save result</h2>
          <ul id="msgs">
          {% endif %}
            <li class="msgs_{{ m.msg_type }}">{{ m.msg_type }} - {{ m.msg }}</li>
          {% if forloop.last %}  
          </ul>
          {% endif %}        
        {% endfor %}

        
        {% block content %}{% endblock %}
    </div>
  </div>


</div>


{% if debugactive == True %}
<div class="container" id="debug">
  <h3>Debug</h3>
  <pre>
  {% block debug %}{% endblock %}
</pre>
</div>
{% endif %}

{% if creditsactive %}
<hr>
<div class="container" id="credits">
VyControl
</div>
{% endif %}


<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>